# Generated by Django 6.0.3 on 2026-03-29 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0004_alter_inventory_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='Product',
            new_name='product',
        ),
    ]
